# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-13 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0002_auto_20160423_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=False)),
                ('old', models.CharField(blank=True, default='', max_length=5)),
                ('parent', models.CharField(blank=True, default='', max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('descr', models.CharField(blank=True, default='', max_length=500)),
                ('is_nsfw', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(related_name='posts', to='anuncios.Category'),
        ),
    ]
