# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-18 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0006_auto_20160616_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
